blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/25K5S55wrU
    about: Join Discord server for support and other.
  - name: Wiki
    url: https://docs.votl.fileeditor.dev
    about: Check out wiki before creating discussions.